name: my_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.8
  provider: ^6.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0 
  hive_flutter: ^1.1.0
  razorpay_flutter: ^1.4.0
  google_fonts: ^6.2.1 
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.6
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.12
  path: ^1.9.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#E0F7F5"
  image: "assets/logo/splash_logo.png"
  android: true
  ios: true